//constants de socis amb noms de variables i errors
export const SOCIS={
    id:"id_soci",
    nom:"nom",
    cog1:"cognom1",
    cog2:"cognom2",
    dni:"DNI",
    sexe:"sexe",
    dNaixement:"data_naixement",
    adreca:"adreca",
    cp:"cp",
    poblacio:"poblacio",
    telefon:"telefon",
    email:"email",
    errors:{
        insert:"hi ha hagut un error al insertar el soci", 
        access:"hi ha hagut un error al intentar accedir",
        modificar:"hi ha hagut un error al intentar modificar el soci",
        validacio:{
            nom:"el nom es obligatori",
            nom_min:"el nom no pot estar buit",
            cog1:"el cognom es obligatori",
            cog1_min:"el cognom no pot estar buit",
            cog2:"el segon cognom es obligatori",
            cog2_min:"el segon cognom no pot estar buit",
            email:"el email es obligatori",
            email_min:"el email no pot tenir menys de 5 caracters",
            email_valid:"es te que escriure un email valid",
            dni:"el DNI es obligatori",
            dni_min:"el DNI no pot tenir menys de 8 caracters",
            sexe:"es te que especificar el sexe",
            sexe_min:"el camp sexe no pot estar buit",
            data_naix:"es te que especificar la data de naixement",
            data_naix_valid:"la data de naixement no es valida",
            cp:"es te que especificar el cp",
            cp_min:"el codi postal te que tenir 5 numeros",
            cp_no_num:"el codi postal te que ser numeric",
            adreca:"es te que especificar l'adreça",
            adreca_min:"l'adreça no pot estar buida",
            poblacio:"es te que especificar l'adreça",
            poblacio_min:"l'adreça no pot estar buida",
            telefon:"el telefon es obligatori",
            telefon_min:"el telefon es masa curt",
        }
    }
}
